### ISSUE TITLE
Your examples/svelte-mpa-app/vite.config.js throw exception

### ISSUE THREAD

**Issue by alvasnet** [IndexXuan/vite-plugin-mpa#37]
1. I download your svelte example
2. change in https://github.com/IndexXuan/vite-plugin-mpa/blob/main/examples/svelte-mpa-app/vite.config.js
`import mpa from '../../src/index'`
to 
`import mpa from 'vite-plugin-mpa'`
3. npm run dev throw exception:
failed to load config from D:\work\js\svelte-mpa-app\vite.config.js
error when starting dev server:
TypeError: (0 , import_vite_plugin_svelte.default) is not a function
    at Object.<anonymous> (D:\work\js\svelte-mpa-app\vite.config.js:41:51)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.require.extensions.<computed> [as .js] (D:\work\js\svelte-mpa-app\node_modules\vite\dist\node\chunks\dep-689425f3.js:62006:20)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (D:\work\js\svelte-mpa-app\node_modules\vite\dist\node\chunks\dep-689425f3.js:62014:17)      
    at loadConfigFromFile (D:\work\js\svelte-mpa-app\node_modules\vite\dist\node\chunks\dep-689425f3.js:61933:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

How to fix this bug?
Thank you!

**Comment by hmalaud** [comment]
Is this problem being looked into by any chance?

**Comment by IndexXuan** [comment]
maybe you are using package.json type=module
